'use client';\n
import { useState } from 'react';\n
export default function HomePage() {\n  const [originalText, setOriginalText] = useState('');\n  const [selectedMood, setSelectedMood] = useState('professional');\n  const [rewrittenText, setRewrittenText] = useState('');\n  const [isLoading, setIsLoading] = useState(false);\n  const [error, setError] = useState('');\n
  const moods = ['chill', 'professional', 'savage', 'flirty', 'dramatic'];\n
  const handleRewrite = async () => {\n    setError('');\n    setRewrittenText('');\n    setIsLoading(true);\n
    try {\n      const response = await fetch('/api/rewrite', {\n        method: 'POST',\n        headers: {\n          'Content-Type': 'application/json',\n        },\n        body: JSON.stringify({ originalText, mood: selectedMood }),\n      });\n
      if (!response.ok) {\n        const errorData = await response.json();\n        throw new Error(errorData.error || 'Something went wrong on the server.');\n      }\n
      const data = await response.json();\n      setRewrittenText(data.rewrittenText);\n    } catch (err) {\n      setError(err.message);\n      console.error('Frontend Fetch Error:', err);\n    } finally {\n      setIsLoading(false);\n    }\n  };\n
  return (\n    <div className="min-h-screen bg-gray-100 p-8 flex flex-col items-center justify-center">\n      <div className="bg-white p-8 rounded-lg shadow-md w-full max-w-2xl">\n        <h1 className="text-3xl font-bold text-gray-800 mb-6 text-center">AI Message Rewriter</h1>\n
        <div className="mb-6">\n          <label htmlFor="originalText" className="block text-gray-700 text-sm font-bold mb-2">\n            Original Message:\n          </label>\n          <textarea\n            id="originalText"\n            className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline resize-none h-32"\n            placeholder="Enter your message here..."\n            value={originalText}\n            onChange={(e) => setOriginalText(e.target.value)}\n          ></textarea>\n        </div>\n
        <div className="mb-6">\n          <label className="block text-gray-700 text-sm font-bold mb-2">\n            Select Mood:\n          </label>\n          <div className="flex flex-wrap gap-4">\n            {moods.map((mood) => (\n              <label key={mood} className="inline-flex items-center">\n                <input\n                  type="radio"\n                  className="form-radio text-blue-600"\n                  name="mood"\n                  value={mood}\n                  checked={selectedMood === mood}\n                  onChange={(e) => setSelectedMood(e.target.value)}\n                />\n                <span className="ml-2 text-gray-700 capitalize">{mood}</span>\n              </label>\n            ))}\n          </div>\n        </div>\n
        <button\n          onClick={handleRewrite}\n          disabled={isLoading || !originalText.trim()}\n          className={`w-full py-3 px-4 rounded-md text-white font-semibold transition duration-300 ${\n            isLoading || !originalText.trim()\n              ? 'bg-gray-400 cursor-not-allowed'\n              : 'bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50'\n          }`}\n        >\n          {isLoading ? 'Rewriting...' : 'Rewrite Message'}\n        </button>\n
        {error && (\n          <div className="mt-4 p-3 bg-red-100 text-red-700 border border-red-400 rounded">\n            Error: {error}\n          </div>\n        )}\n
        {rewrittenText && (\n          <div className="mt-6 p-4 bg-gray-50 rounded-md border border-gray-200">\n            <h3 className="text-lg font-semibold text-gray-800 mb-2">Rewritten Message:</h3>\n            <p className="text-gray-700 whitespace-pre-wrap">{rewrittenText}</p>\n          </div>\n        )}\n      </div>\n    </div>\n  );\n}